disable jobs to test chart generation, add git-credentials file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,82 +5,87 @@ stages:
 default:
   tags:
     - kubernetes
+# TODO: Reenable after we're finished testing chart generation
+# build-dev-environment:
+#   image: registry.sandbox.labz.s-box.org/vcaaron/flaskr/nix:2.24.9
+#   stage: build
+#   rules:
+#     - changes:
+#       - dev/flake.nix
+#       - dev/flake.lock
+#       - dev/packages.nix
+#       - .gitlab-ci.yml
+#   script:
+#       #install needed tools
+#     - nix-env --install --attr nixpkgs.skopeo
+#     - |
+#       mkdir -p "$HOME/.config/nix"
+#       printf "experimental-features = nix-command flakes" > "$HOME/.config/nix/nix.conf"
+#       mkdir -p "/etc/containers"
+#       echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
+#       git config --global --add safe.directory "$(pwd)"
+#     - cd dev
 
-build-dev-environment:
-  image: registry.sandbox.labz.s-box.org/vcaaron/flaskr/nix:2.24.9
-  stage: build
-  rules:
-    - changes:
-      - dev/flake.nix
-      - dev/flake.lock
-      - dev/packages.nix
-      - .gitlab-ci.yml
-  script:
-      #install needed tools
-    - nix-env --install --attr nixpkgs.skopeo
-    - |
-      mkdir -p "$HOME/.config/nix"
-      printf "experimental-features = nix-command flakes" > "$HOME/.config/nix/nix.conf"
-      mkdir -p "/etc/containers"
-      echo '{"default":[{"type":"insecureAcceptAnything"}]}' > /etc/containers/policy.json
-      git config --global --add safe.directory "$(pwd)"
-    - cd dev
+#     # build dev and testing environments
+#     - nix build --eval-system x86_64-linux --show-trace .#default -o polar-dev 
+    
+#     #  Use skopeo to inspect and upload our images
+#     - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
+#     - skopeo inspect docker-archive://$(readlink -f ./polar-dev)
+#     - skopeo copy docker-archive://$(readlink -f ./polar-dev) docker://$CI_REGISTRY_IMAGE/polar-dev:0.1.0
 
-    # build dev and testing environments
-    - nix build --eval-system x86_64-linux --show-trace .#default -o polar-dev 
+# build-workspace:
+#   image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-ci:0.1.0
+#   stage: build
+#   variables:
+#   script:
+#     - git config --global --add safe.directory "$(pwd)"
     
-    #  Use skopeo to inspect and upload our images
-    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
-    - skopeo inspect docker-archive://$(readlink -f ./polar-dev)
-    - skopeo copy docker-archive://$(readlink -f ./polar-dev) docker://$CI_REGISTRY_IMAGE/polar-dev:0.1.0
-
-build-workspace:
-  image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-ci:0.1.0
-  stage: build
-  variables:
-  script:
-    - git config --global --add safe.directory "$(pwd)"
+#     - cd src/agents
+#     # build workspace
+#     - nix build --eval-system x86_64-linux --show-trace .#default
     
-    - cd src/agents
-    # build workspace
-    - nix build --eval-system x86_64-linux --show-trace .#default
+#     # Vulnerability analysis on our store
+#     # vulnix returns nonzero exit codes, so we need to get around this.
+#     # SEE: https://github.com/nix-community/vulnix/issues/79
+#     - vulnix --json result > vulnix-report.json || export VULNIX_EXIT=$?
+#     - |
+#       if [[ "$VULNIX_EXIT" -eq 2 ]]; then
+#         echo "Non-whitelisted vulnerabilities found!"
+#       elif [[ "$VULNIX_EXIT" -eq 1 ]]; then
+#         echo "Only whitelisted vulnerabilities found."
+#       elif [[ "$VULNIX_EXIT" -eq 0 ]]; then
+#         echo "Nothing found, is the store empty?"  
+#       fi
     
-    # Vulnerability analysis on our store
-    # vulnix returns nonzero exit codes, so we need to get around this.
-    # SEE: https://github.com/nix-community/vulnix/issues/79
-    - vulnix --json result > vulnix-report.json || export VULNIX_EXIT=$?
-    - |
-      if [[ "$VULNIX_EXIT" -eq 2 ]]; then
-        echo "Non-whitelisted vulnerabilities found!"
-      elif [[ "$VULNIX_EXIT" -eq 1 ]]; then
-        echo "Only whitelisted vulnerabilities found."
-      elif [[ "$VULNIX_EXIT" -eq 0 ]]; then
-        echo "Nothing found, is the store empty?"  
-      fi
-    
-    # using already built dependencies, package and containerize our components.
-    - nix build --eval-system x86_64-linux --show-trace .#cassiniImage -o cassini
-    - nix build --eval-system x86_64-linux --show-trace .#observerImage -o observer
-    - nix build --eval-system x86_64-linux --show-trace .#consumerImage -o consumer
-    - ls -lh
-    # Use skopeo to inspect and upload our images
-    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
-    - | 
-      skopeo inspect docker-archive://$(readlink -f cassini)
-      skopeo copy docker-archive://$(readlink -f cassini) docker://$CI_REGISTRY_IMAGE/cassini:0.1.0
-      skopeo inspect docker-archive://$(readlink -f observer)
-      skopeo copy docker-archive://$(readlink -f observer) docker://$CI_REGISTRY_IMAGE/polar-gitlab-observer:0.1.0
-      skopeo inspect docker-archive://$(readlink -f consumer)
-      skopeo copy docker-archive://$(readlink -f consumer) docker://$CI_REGISTRY_IMAGE/polar-gitlab-consumer:0.1.0
-  artifacts:
-    paths:
-      - src/agents/vulnix-report.json
+#     # using already built dependencies, package and containerize our components.
+#     - nix build --eval-system x86_64-linux --show-trace .#cassiniImage -o cassini
+#     - nix build --eval-system x86_64-linux --show-trace .#observerImage -o observer
+#     - nix build --eval-system x86_64-linux --show-trace .#consumerImage -o consumer
+#     - ls -lh
+#     # Use skopeo to inspect and upload our images
+#     - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
+#     - | 
+#       skopeo inspect docker-archive://$(readlink -f cassini)
+#       skopeo copy docker-archive://$(readlink -f cassini) docker://$CI_REGISTRY_IMAGE/cassini:0.1.0
+#       skopeo inspect docker-archive://$(readlink -f observer)
+#       skopeo copy docker-archive://$(readlink -f observer) docker://$CI_REGISTRY_IMAGE/polar-gitlab-observer:0.1.0
+#       skopeo inspect docker-archive://$(readlink -f consumer)
+#       skopeo copy docker-archive://$(readlink -f consumer) docker://$CI_REGISTRY_IMAGE/polar-gitlab-consumer:0.1.0
+#   artifacts:
+#     paths:
+#       - src/agents/vulnix-report.json
 
 generate-charts:
   image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-ci:0.1.0
   stage: charts
-  
   script:
+    - |
+      git config user.email $GITLAB_USER_EMAIL
+      git config user.name "gitlab-ci-job"
+
+    - echo "https://$POLAR_DEPLOY_USER:$CHART_REPO_TOKEN@gitlab.sandbox.labz.s-box.org/sei/polar-deploy.git" > ~/.git-credentials
+
     # Clone the chart repo
     # NOTE: A deploy key should be used used to enable read/write perms
     # An access token will do in the meantime
@@ -109,9 +114,6 @@ generate-charts:
     
     # Commit and push if there are changes
     - |
-      git config user.email $GITLAB_USER_EMAIL
-      git config user.name "gitlab-ci-job"
-      
       git add chart/metadata.yaml
       git add .
       echo "Updated files:"
