don't exit from vulnix results

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -74,22 +74,16 @@ build-workspace:
     - 'nix build --eval-system x86_64-linux --show-trace .#default'
     
     # Vulnerability analysis on our store
-    # vulnix returns nonzero exit codes when it finds things, so we need to get around this.
+    # vulnix returns nonzero exit codes, so we need to get around this.
     # SEE: https://github.com/nix-community/vulnix/issues/79
-    - vulnix --json > vulnix-report.json || export VULNIX_EXIT=$?
+    - vulnix --json result > vulnix-report.json || export VULNIX_EXIT=$?
     - |
       if [[ "$VULNIX_EXIT" -eq 2 ]]; then
         echo "Non-whitelisted vulnerabilities found!"
-        exit 1  # Fail the job
       elif [[ "$VULNIX_EXIT" -eq 1 ]]; then
-        echo "Only whitelisted vulnerabilities found, continuing..."
-        exit 0  # Continue without failing
+        echo "Only whitelisted vulnerabilities found."
       elif [[ "$VULNIX_EXIT" -eq 0 ]]; then
-        echo "No vulnerabilities found, all good."
-        exit 0
-      else
-        echo "Unexpected error occurred!"
-        exit $VULNIX_EXIT  # Fail the job with original exit code
+        echo "Nothing found, is the store empty?"  
       fi
     
     # using already built dependencies, package and containerize our components.
